server.port=8080

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=920234632283-q9c7cufp5etflqc576e8ddg3dh74p7e3.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

server.servlet.jsp.init-parameters.development=true